services:
  logdy:
    build:
      context: https://github.com/logdyhq/logdy-core.git
    container_name: logdy
    restart: unless-stopped
    volumes:
      - ../proxy-caddy/logs:/logs:ro
    command:
      - "follow"
      - "/logs/api-access.log"
    ports:
      - "8080:8080"
    networks:
      - proxy-net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
 
networks:
  proxy-net:
    external: true
